#!/usr/bin/env node
/**
 * generate-app.mjs — materialize one coach's native project from its registry.
 *
 *   node scripts/generate-app.mjs <slug>
 *
 * Reads mobile/coaches/<slug>.json and writes:
 *   mobile/generated/<slug>/capacitor.config.ts  (values inlined → reproducible build)
 *   mobile/generated/<slug>/assets.json          (icon/splash inputs for @capacitor/assets)
 *
 * It does NOT run native builds (no Xcode/Android SDK here). CI / a Mac runs
 * `cap add` + `cap sync` + Fastlane against the generated config.
 */
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const REQUIRED = ["slug", "appId", "appName", "memberUrl"];

function fail(message) {
  console.error(`✗ ${message}`);
  process.exit(1);
}

async function main() {
  const slug = process.argv[2];
  if (!slug) fail("Usage: node scripts/generate-app.mjs <slug>");

  const registryPath = join(ROOT, "coaches", `${slug}.json`);
  let coach;
  try {
    coach = JSON.parse(await readFile(registryPath, "utf8"));
  } catch {
    fail(`No registry found at coaches/${slug}.json (run \`pnpm sync\` first or create it).`);
  }

  const missing = REQUIRED.filter((key) => !coach[key]);
  if (missing.length) fail(`Registry coaches/${slug}.json is missing: ${missing.join(", ")}`);

  const themeColor = coach.themeColor ?? coach.backgroundColor ?? "#0d0d10";
  const backgroundColor = coach.backgroundColor ?? themeColor;

  const outDir = join(ROOT, "generated", slug);
  await mkdir(outDir, { recursive: true });

  const config = `import type { CapacitorConfig } from "@capacitor/cli";

// AUTO-GENERATED by mobile/scripts/generate-app.mjs for "${coach.slug}". Do not edit by hand.
const config: CapacitorConfig = {
  appId: ${JSON.stringify(coach.appId)},
  appName: ${JSON.stringify(coach.appName)},
  webDir: "www",
  server: { url: ${JSON.stringify(coach.memberUrl)}, cleartext: false },
  backgroundColor: ${JSON.stringify(backgroundColor)},
  ios: { contentInset: "always" },
  android: { backgroundColor: ${JSON.stringify(backgroundColor)} },
  plugins: {
    SplashScreen: { launchAutoHide: true, backgroundColor: ${JSON.stringify(backgroundColor)}, showSpinner: false },
    StatusBar: { style: "DARK", backgroundColor: ${JSON.stringify(themeColor)} },
  },
};

export default config;
`;
  await writeFile(join(outDir, "capacitor.config.ts"), config, "utf8");

  // @capacitor/assets inputs: it reads assets/icon.(png|svg) + a background color.
  const assets = {
    icon: coach.iconSource ?? null,
    iconBackgroundColor: backgroundColor,
    splashBackgroundColor: backgroundColor,
    note: "Place a 1024x1024 icon at generated/" + slug + "/assets/icon.png (download iconSource), then run `npx @capacitor/assets generate`.",
  };
  await writeFile(join(outDir, "assets.json"), JSON.stringify(assets, null, 2) + "\n", "utf8");

  console.log(`✓ Generated generated/${slug}/capacitor.config.ts (server.url=${coach.memberUrl})`);
  console.log(`  Next: download the 1024px icon to generated/${slug}/assets/icon.png, then on a Mac/CI:`);
  console.log(`    cd mobile && npx cap add ios && npx cap add android && npx cap sync`);
  console.log(`    npx @capacitor/assets generate --assetPath generated/${slug}/assets`);
  console.log(`    fastlane ios   coach:${slug}`);
  console.log(`    fastlane android coach:${slug}`);
}

main();
